name = "SuffixConversion"
uuid = "a5344401-2eb1-4dab-b845-3affa8d070e0"
authors = ["Simon Byrne <simonbyrne@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
